### ISSUE TITLE
Can't run juju bootstrap on macbook pro

### ISSUE THREAD

**Issue by dlmoody** [kapilt/juju-digitalocean#31]
I am completely new to this juju.
I got everythin installed or so i thought but once i run the bootstrap command i get an error. Here is my command screen:

```
┌─[davidmoody][75-105-255-176][~]
└─▪ sudo pip install juju-docean
Password:
The directory '/Users/davidmoody/Library/Logs/pip' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/davidmoody/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/davidmoody/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Collecting juju-docean
  Downloading juju-docean-0.5.1.tar.gz
Collecting PyYAML (from juju-docean)
  Downloading PyYAML-3.11.tar.gz (248kB)
    100% |################################| 249kB 570kB/s
Collecting requests (from juju-docean)
  Downloading requests-2.5.1-py2.py3-none-any.whl (464kB)
    100% |################################| 466kB 521kB/s
Installing collected packages: requests, PyYAML, juju-docean

  Running setup.py install for PyYAML
    checking if libyaml is compilable
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c build/temp.macosx-10.9-intel-2.7/check_libyaml.c -o build/temp.macosx-10.9-intel-2.7/check_libyaml.o
    build/temp.macosx-10.9-intel-2.7/check_libyaml.c:2:10: fatal error: 'yaml.h' file not found
    #include <yaml.h>
             ^
    1 error generated.
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
  Running setup.py install for juju-docean
    Installing juju-docean script to /usr/local/bin
Successfully installed PyYAML-3.11 juju-docean-0.5.1 requests-2.5.1
┌─[davidmoody][75-105-255-176][~]
└─▪ juju switch digitalocean
amazon -> digitalocean
┌─[davidmoody][75-105-255-176][~]
└─▪ juju docean bootstrap --constraints="mem=2G, region=nyc2"
Traceback (most recent call last):
  File "/usr/local/bin/juju-docean", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests
ERROR subprocess encountered error code 1
```

I think it is some kind of permission problem? maybe? just have no idea how to fix it.

**Comment by dlmoody** [comment]
BTW,
I reran the install command for juju-docean and got this.

```
┌─[davidmoody][75-105-255-176][~]
└─▪ sudo pip install -U juju-docean
Password:
The directory '/Users/davidmoody/Library/Logs/pip' or its parent directory is not owned by the current user and the debug log has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/davidmoody/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
The directory '/Users/davidmoody/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want the -H flag.
Requirement already up-to-date: juju-docean in /Library/Python/2.7/site-packages
Requirement already up-to-date: PyYAML in /Library/Python/2.7/site-packages (from juju-docean)
Requirement already up-to-date: requests in /Library/Python/2.7/site-packages (from juju-docean)
```
but i still get the same error:

```
┌─[davidmoody][75-105-255-176][~]
└─▪ juju docean bootstrap --constraints="mem=2G, region=nyc2"
Traceback (most recent call last):
  File "/usr/local/bin/juju-docean", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: requests
ERROR subprocess encountered error code 1

```

**Comment by dlmoody** [comment]
Fixed it

ran this
```
sudo easy_install --upgrade requests
```
just in case anyone else has this issue

**Comment by kapilt** [comment]
thanks for the report, i'll try and reproduce to smooth this out for future
users.
